### ISSUE TITLE
Docker image for Synquid

### ISSUE THREAD

**Issue by yinengy** [nadia-polikarpova/synquid#2]
Setting up Synquid environment is painful and time consuming.
So, I made a docker image for those who have troubling compile Synquid from source code. Feel free to use it.

https://hub.docker.com/repository/docker/yinengy/synquid

Usage:
```
docker run --name synquid -it yinengy/synquid
synquid <your_program_filename>
```

**Comment by yinengy** [comment]
And the demo server is down since yesterday.

**Comment by nadia-polikarpova** [comment]
Thanks a bunch! I'll add a link to readme. Also I have restarted the server.

**Comment by nadia-polikarpova** [comment]
Oh wait, the server it still not working properly, let me investigate.

**Comment by yinengy** [comment]
Thanks!
